### ISSUE TITLE
Extra log in the current master head

### ISSUE THREAD

**Issue by pb-jchin** [PacificBiosciences/DALIGNER#10]
I just checkout the master head (7ef40d8f904f16338de7bab1647429c222a9379f).  There is too much log output.  We should not set extra log output as default.

**Comment by pb-jchin** [comment]
@pb-cdunn  I see what you like to output.  I think we need a "-vv" like output. The orginal "-v" log has some good information about the overlap statistics which is useful for assembling repetitive genome. I like to keep those. For the memory operation log, we need a different option. Any thought about this?

**Comment by pb-cdunn** [comment]
'-v', or simply '-v -v', is a good idea. I can look into that next week.

**Comment by pb-jchin** [comment]
thask. I will be tagging a 0.4 soon after a couple checking up.
