### ISSUE TITLE
What's the meaning of the -H option of LA4Falcon? 

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/DALIGNER#27]
Finally, I find this place. The module LA4Falcon is a tool developed by engineers of PB company and only exists in the forked version of Daligner.

I check the sequences in the output of LA4Falcon and find that there are some sequences whose length is less than the CUTOFF I set.
So What's the meaning of the -H option of LA4Falcon?

I have read the following words in your website, but it's not clear enough.
‘’Output data from a Dazzler DB into fasta format for FALCON. You can supply the argument -H with an integer value to filter reads below a given threshold.‘’
But how to filter?

**Comment by pb-cdunn** [comment]
I think `-H` is archaic. It no longer does anything in **LA4Falcon**.
