### ISSUE TITLE
daligner seg fault (non-default parameters)

### ISSUE THREAD

**Issue by Magdoll** [PacificBiosciences/DALIGNER#3]
daligner seg faults/memory corruption on the following parameter set:

daligner -k24 a.fasta.1 b.fasta.1

On default parameters however it runs fine:

daligner a.fasta.1 b.fasta.1

Note that b.fasta has only 1 seq. 

My suspicion is this might have to do with highly repetitive k-mers, though I'm not sure why inceasing the k-mer size actually causes the seg fault.

fasta files:
https://dl.dropboxusercontent.com/u/47842021/random/a.fasta
https://dl.dropboxusercontent.com/u/47842021/random/b.fasta

Daligner used was commit d4aa4871122b35ac92e2cc13d9b1b1e9c5b5dc5c
(Jun 15 2015 commit)

**Comment by pb-cdunn** [comment]
Yes, the daligner settings can be finicky. We hope to provide some automated help with those settings eventually.

I might pull your dropbox data for a test-case someday. Hopefully, you can keep it available for a few weeks. But I'll mark this issue as "closed". It's still available in GitHub.
