### ISSUE TITLE
Memory clobber?

### ISSUE THREAD

**Issue by TomSkelly** [PacificBiosciences/DALIGNER#9]
daligner invoked from PacBio IsoSeq fails with the one-line error:

**\* glibc detected **\* daligner: malloc(): memory corruption: 0x00000000012623e0 ***

... not too helpful. So I ran it through valgrind (after compiling with the -g option). valgrind found several errors, including several invalid reads and writes by filter.c, lines 218 to 227.

I then noticed that my four valgrind runs had produced different outputs. In each case, there were two bad writes and six bad reads. But the grouping of the errors by thread was different: In one case, 5 on one thread and 3 on another. In the next case, all 8 on one thread. In two more cases, 2+6.

The code is too obscure for me to decipher further (too many single-character variable names!). But I see a lot of static variables. Given that all threads share one copy of a static variable, I'm now nervous.

I changed NTHREADS to 1 and NSHIFT to 0 in filter.h, so that only one thread is run. valgrind now runs without the invalid read/write errors (although some heap allocation complaints remain). So I suspect the threads are colliding with each other when accessing the static variables.

I don't seem to be able to attach text files to this github issue, so I've emailed them to Liz. There are four different valgrind output, plus the clean, single-threaded  one.

**Comment by TomSkelly** [comment]
Forgot to include the command I ran:

valgrind --leak-check=yes daligner -h35 -k16 -e.80 -l300 -s100 -t10 /is2/projects/pacbio/scratch/skellytf/data/KRAS/2015-07-31a_839/B03_redux/IsoCluster-20150824-142850/cluster/input.split_000.dazz.fasta.1 /is2/projects/pacbio/scratch/skellytf/data/KRAS/2015-07-31a_839/B03_redux/IsoCluster-20150824-142850/cluster/ref_consensus.dazz.fasta.1

**Comment by pb-cdunn** [comment]
If Liz has the input FASTA files (inputs to dazz_db) I'll try to look at this next week.

Which daligner are you using? From cDNA_primer, or from PacificBiosciences/DALIGNER?

**Comment by TomSkelly** [comment]
I'm using the one that came with cDNA_primer, DALIGNER-d4aa4871122b35ac92e2cc13d9b1b1e9c5b5dc5c-ICEmod.

**Comment by pb-cdunn** [comment]
If possible, download and build https://github.com/PacificBiosciences/DALIGNER

If that works for you, then we'll definitely upgrade to that during September. Otherwise, I'll debug sometime this month, using your test-case.

**Comment by Magdoll** [comment]
Chris, if you can confirm the newer version works let me know. I/we can upgrade it later and keep the right dependency on ToFU.

**Comment by TomSkelly** [comment]
I see I closed this by mistake. Reopening it.

--TS

**Comment by pb-cdunn** [comment]
How can I get the fasta file? I think I need to reproduce the dazzdb too. Can you give us a full test-case for DALIGNER?

**Comment by TomSkelly** [comment]
The attached tar file includes daligner input files, the command used to
run it under valgrind, and the valgrind output. You will need to change the
directory names in the command.

--TS

**Comment by pb-cdunn** [comment]
When it blows up, it crashes. Sometimes a bit of tweaking is requried.

```
# This fails:
C:=$D -h35 -k16 -e.80 -l300 -s100 -t10 input.split_000.dazz.fasta.1 ref_consensus.dazz.fasta.1
# These work:
C:=$D -h26 -k16 -e.80 -l300 -s100 -t10 input.split_000.dazz.fasta.1 ref_consensus.dazz.fasta.1
C:=$D -h35 -k16 -e.80 -l300 -s1 -t10 input.split_000.dazz.fasta.1 ref_consensus.dazz.fasta.1
C:=$D -h35 -k16 -e.80 -l300 -s100 -t20 input.split_000.dazz.fasta.1 ref_consensus.dazz.fasta.1
C:=$D -h35 -k16 -e.80 -l300 -s100 -t1 input.split_000.dazz.fasta.1 ref_consensus.dazz.fasta.1
```

Some of those will produce bad results, but I suspect `-t20` is ok and `-h26` might be interesting.

But you're right: It passes with `NTHREADS=1 NSHIFT=0`. I'll look into this more deeply when I have time. Thanks for the useful test-case.

**Comment by pb-cdunn** [comment]
Brief status update:
1. I don't think there is a real MT bug. Instead, I think a kind of buffer over-run causes one thread to write into another thread's data.
2. I think that occurs because an index array (tptr) is not properly initialized for some extreme cases.

I hope to solve this next week.

**Comment by TomSkelly** [comment]
Sounds good.

I haven't been back in touch as I've been out with the flu (or whatever)
for the last week. I hope to make it back tomorrow (Mon).

--TS

**Comment by pb-cdunn** [comment]
We've solved this and will patch it soon. The bug occurs when the hit-count is less than NTHREADS. From a successful run:

```
Comparing input.split_000.dazz.fasta.1 to ref_consensus.dazz.fasta.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 266
   Highwater of 0.01Gb space

     266 16-mers (1.363071e-09 of matrix)
       2 seed hits (1.024866e-11 of matrix)
       4 confirmed hits (2.049731e-11 of matrix)

Comparing c(input.split_000.dazz.fasta.1) to ref_consensus.dazz.fasta.1

   Capping mutual k-mer matches over 10000 (effectively -t100)
   Hit count = 1
   Highwater of 0.01Gb space

     1 16-mers (5.124328e-12 of matrix)
     0 seed hits (0.000000e+00 of matrix)
     0 confirmed hits (0.000000e+00 of matrix)
```

The complement-direction had only 1 hit. There is a bug in the code which splits the jobs into threads when nhits < NTHREADS. The fix will be pushed soon. With that fix, there are no valgrind-memcheck errors (except unfreed memory), nor helgrind errors, nor any data-races detected. (There is something in rewind() syscall, but that might not be us at all.)

**Comment by TomSkelly** [comment]
That is a very nice job of debugging -- sounds like you had some fun.  I'll
watch for the patch.

-- Tom Skelly

**Comment by pb-cdunn** [comment]
Your test-case was invaluable. Thanks for that.

You can see why this never came up before. But I definitely like to have some small test-cases.
